ReflectionProperty stateDataToStateIdLookup
ReflectionException: "Property pocketmine\network\mcpe\convert\BlockStateDictionary::$stateDataToStateIdLookupCache does not exist"